name: "Flutter ToDo app"

on:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: '16'
          distribution: 'zulu'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get
      - name: Build android apk and appBundle
        run: flutter build apk
      - name: Build ios
        run: | 
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Push to releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/app/outputs/flutter-apk/app-release.apk, build/ios/app.ipa'
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.GH_TOKEN }}