name: "Flutter ToDo app"

on:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    name: Build Apk and IOS
    runs-on: macos-latest
    outputs:
      androidApk: ${{ steps.android.outputs.apk }}
      iosBuildFile: ${{ steps.ios.outputs.apk }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: '16'
          distribution: 'zulu'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - run: flutter --version

      - name: Install dependencies #this should be one job
        run: flutter pub get
      - name: Build android apk and appBundle #this should be separate job
        id: android
        run: |
          flutter build apk
          echo "::set-output name=apk::$( cat build/app/outputs/flutter-apk/app-release.apk) "

      - name: Build ios #this one also, since only jobs can run in parallel
        id: ios
        run: | 
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
          echo "::set-output name=apk::$( cat build/ios/app.ipa )"
      - name: Push to releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/app/outputs/flutter-apk/app-release.apk, build/ios/app.ipa'
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.GH_TOKEN }}

  release:
    name: Release to Firebase Distribution
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create Android apk
        run: echo ${{ needs.build.outputs.androidApk }} > app-release.apk
      - name: Upload Android artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.ANDROID_APPID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app-release.apk

      - name: Create Ios ipa
        run: echo ${{ needs.build.outputs.iosBuildFile }} > app.ipa
      - name: Upload IOS artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.IOS_APPID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app.ipa
